// Extracted from BARCODES screening/show.blade.php

export const NTG_LEVEL1_OPTIONS = [
  "Anaemia And Nutritional Conditions",
  "Cardiovascular Disorders",
  "Conditions Of The Ear, Nose And Oropharynx",
  "Dermatological Conditions",
  "Disorders Of The Renal System",
  "Urology disorders",
  "Eye Disease",
  "Gastro-intestinal conditions",
  "Infections",
  "Malignancies",
  "Orthopedic conditions",
  "Obstetric & Gynaecological conditions",
  "Poisoning",
  "Surgical conditions",
  "Haematological conditions",
  "Dental conditions",
  "Mental health and psychiatric disorders",
  "Endocrine disorders"
] as const

export type NtgLevel1 = (typeof NTG_LEVEL1_OPTIONS)[number]

export const CHRONIC_LEVEL2_BY_LEVEL1: Record<string, string[]> = {
        'Anaemia And Nutritional Conditions': ['Anaemia', 'Malnutrition', 'Vitamin deficiencies'],
        'Cardiovascular Disorders': ['Angina pectoris', 'Cardiac arrhythmias', 'Congestive heart failure', 'Hypertension', 'Infective endocarditis', 'Myocardial infarction', 'Pulmonery oedema', 'Rheumatic fever'],
        'Conditions Of The Ear, Nose And Oropharynx': ['Ear conditions', 'Nasal diseases', 'oral disease', 'Pharyngeal diseases'],
        'Dermatological Conditions': ['bacterial infections', 'Fungal Infection', 'Parasitic infections', 'viral skin infections'],
        'Disorders Of The Renal System': ['GLOMERULAR DISORDERS', 'Catheter-related bloodstream infections (CRBSI)', 'hypertension', 'Metabolic disorders', 'Renal and pancreatic transplant'],
        'Urology disorders': ['Renal and pancreatic transplant'],
        'Eye Disease': ['Glaucoma', 'ocular emergencies', 'Optics & refraction (Refractive errors and low vision)', 'strabismus (squint)', 'systemic eye disease and the eye', 'the red eye', 'Trachoma'],
        'Gastro-intestinal conditions': ['Abdominal Pain', 'Cholera', 'Diarrhoea', 'Dysentery', 'Epilepsy', 'Febrile Convulsions', 'Giardiasis', 'Helminth Infestation', 'Mental health and psychiatric illnesses', 'Mood disorders', 'Pyschotic Disorder', 'Rabies'],
        'Infections': ['Anthrax', 'Malaria', 'Meningitis', 'Sexually transmitted infections', 'The plague', 'Tuberculosis', 'Cholera'],
        'Malignancies': ['Anal cancer', 'Astrocytomas', 'Carcinoma of the Breast', 'Cervical cancer', 'Colorectal carcinoma', 'endometrial cancer', 'Gastric cancer', 'leukaemias', 'Lung cancer', 'lymphomas', 'Nasopharyngeal carcinoma', 'Oesophageal Cacinoma', 'Ovarian cancer', 'Paediatric cancer', 'pancreatic cancer', 'prostate cancer', 'testicular cancer', 'thyroid cancer'],
        'Orthopedic conditions': ['Renal and pancreatic transplant'],
        'Obstetric & Gynaecological conditions': ['Abortion', 'Antenatal care', 'Antepartum haemorrhage (APH)', 'Medical disease in pregnancy', 'Menstrual disorders', 'Normal labour', 'Postpartum haemorrhage (PPH)', 'Pre-eclapsia and eclampsia'],
        'Poisoning': ['Management of a poisned patient', 'treatment of specific common poisoning'],
        'Surgical conditions': ['Acute mumps orchitis', 'Bites', 'Hydrocele', 'injuries', 'Strangulated hernia', 'Testicular torsion', 'testicular tumours', 'varicocele'],
        'Haematological conditions': ['Renal and pancreatic transplant'],
        'Dental conditions': ['Facial fractures', 'Hard tissue conditions', 'Soft tissue conditions', 'Tumors-benign', 'Tumors-malignant'],
        'Mental health and psychiatric disorders': [],
        'Endocrine disorders': [],
    };

export const CHRONIC_LEVEL3_BY_LEVEL2: Record<string, string[]> = {
        // Anaemia And Nutritional Conditions
        'Anaemia': ['Iron deficiency anaemia', 'Megaloblastic anaemia', 'Normocytic anaemia', 'Aplastic anaemia', 'Haemolytic anaemia', 'Sickle cell anaemia'],
        'Malnutrition': ['Kwashiorkor', 'Marasmus', 'Marasmic kwashiorkor', 'Wasting', 'Stunting', 'Obesity'],
        'Vitamin deficiencies': ['Vitamin A deficiency', 'Vitamin B1 (Thiamine) deficiency', 'Vitamin B12 deficiency', 'Vitamin C deficiency (Scurvy)', 'Vitamin D deficiency (Rickets)'],
        // Cardiovascular Disorders
        'Angina pectoris': ['Stable angina', 'Unstable angina'],
        'Cardiac arrhythmias': ['Atrial fibrillation', 'Atrial flutter', 'Supraventricular tachycardia', 'Ventricular tachycardia', 'Ventricular fibrillation', 'Heart block', 'Sinus bradycardia'],
        'Cardiopulmonary resuscitation and advanced cardiac life support': ['Basic life support', 'Advanced cardiac life support', 'Post-resuscitation care'],
        'Congestive heart failure': ['Left ventricular failure', 'Right ventricular failure', 'Biventricular failure'],
        'Hypertension': ['Mild hypertension', 'Moderate hypertension', 'Severe hypertension', 'Hypertensive emergency', 'Hypertensive urgency'],
        'Infective endocarditis': ['Native valve endocarditis', 'Prosthetic valve endocarditis'],
        'Myocardial infarction': ['ST-elevation myocardial infarction (STEMI)', 'Non-ST-elevation myocardial infarction (NSTEMI)'],
        'Pulmonery oedema': ['Acute pulmonary oedema'],
        'Rheumatic fever': ['Acute rheumatic fever', 'Rheumatic heart disease'],
        // Conditions Of The Ear, Nose And Oropharynx
        'Ear conditions': ['Acute otitis media', 'Chronic suppurative otitis media', 'Otitis externa', 'Serous otitis media', 'Hearing loss'],
        'Nasal diseases': ['Allergic rhinitis', 'Epistaxis', 'Acute sinusitis', 'Chronic sinusitis', 'Nasal polyps'],
        'oral disease': ['Gingivitis', 'Periodontitis', 'Oral candidiasis', 'Aphthous ulcers', 'Dental abscess'],
        'Pharyngeal diseases': ['Acute pharyngitis', 'Tonsillitis', 'Peritonsillar abscess', 'Epiglottitis'],
        // Dermatological Conditions
        'bacterial infections': ['Impetigo', 'Cellulitis', 'Erysipelas', 'Folliculitis', 'Boil (furuncle)', 'Carbuncle', 'Leprosy'],
        'Fungal Infection': ['Tinea capitis', 'Tinea corporis (ringworm)', 'Tinea pedis (athlete\'s foot)', 'Pityriasis versicolor', 'Candidiasis'],
        'Parasitic infections': ['Scabies', 'Pediculosis (lice)', 'Cutaneous larva migrans'],
        'viral skin infections': ['Herpes zoster (shingles)', 'Herpes simplex', 'Chickenpox', 'Warts', 'Molluscum contagiosum'],
        // Disorders Of The Renal System
        'GLOMERULAR DISORDERS': ['Acute glomerulonephritis', 'Nephrotic syndrome', 'Chronic kidney disease'],
        'Catheter-related bloodstream infections (CRBSI)': ['Prevention of CRBSI', 'Treatment of CRBSI'],
        'hypertension': ['Renovascular hypertension', 'Renal hypertension'],
        'Metabolic disorders': ['Renal calculi (kidney stones)', 'Gout', 'Hyperuricaemia'],
        'Renal and pancreatic transplant': ['Pre-transplant management', 'Post-transplant care', 'Rejection management'],
        // Eye Disease
        'Glaucoma': ['Primary open-angle glaucoma', 'Acute angle-closure glaucoma', 'Secondary glaucoma', 'Congenital glaucoma'],
        'ocular emergencies': ['Chemical eye injury', 'Penetrating eye injury', 'Retinal detachment', 'Central retinal artery occlusion'],
        'Optics & refraction (Refractive errors and low vision)': ['Myopia', 'Hyperopia', 'Astigmatism', 'Presbyopia', 'Low vision'],
        'strabismus (squint)': ['Esotropia', 'Exotropia', 'Mixed strabismus'],
        'systemic eye disease and the eye': ['Diabetic retinopathy', 'Hypertensive retinopathy', 'HIV-related eye disease', 'Thyroid eye disease'],
        'the red eye': ['Conjunctivitis', 'Keratitis', 'Anterior uveitis', 'Episcleritis'],
        'Trachoma': ['Active trachoma', 'Cicatricial trachoma', 'Trachomatous trichiasis'],
        // Gastro-intestinal conditions
        'Abdominal Pain': ['Acute appendicitis', 'Peptic ulcer disease', 'Irritable bowel syndrome', 'Intestinal obstruction', 'Cholecystitis', 'Pancreatitis'],
        'Cholera': ['Cholera (severe dehydration)', 'Cholera (some dehydration)', 'Cholera (no dehydration)'],
        'Diarrhoea': ['Acute watery diarrhoea', 'Persistent diarrhoea', 'Chronic diarrhoea'],
        'Dysentery': ['Amoebic dysentery', 'Bacillary dysentery (Shigellosis)'],
        'Epilepsy': ['Generalised tonic-clonic seizures', 'Absence seizures', 'Partial seizures', 'Status epilepticus'],
        'Febrile Convulsions': ['Simple febrile convulsions', 'Complex febrile convulsions'],
        'Giardiasis': ['Giardia intestinalis infection'],
        'Helminth Infestation': ['Ascariasis', 'Hookworm infection', 'Tapeworm (Taeniasis)', 'Trichuriasis', 'Strongyloides'],
        'Mental health and psychiatric illnesses': ['Major depressive disorder', 'Anxiety disorder', 'Schizophrenia', 'Bipolar disorder'],
        'Mood disorders': ['Major depressive disorder', 'Persistent depressive disorder (dysthymia)', 'Bipolar I disorder', 'Bipolar II disorder'],
        'Pyschotic Disorder': ['Schizophrenia', 'Schizophreniform disorder', 'Brief psychotic disorder', 'Schizoaffective disorder'],
        'Rabies': ['Post-exposure prophylaxis', 'Established rabies'],
        // Infections
        'Anthrax': ['Cutaneous anthrax', 'Inhalation anthrax', 'Gastrointestinal anthrax'],
        'Malaria': ['Uncomplicated malaria', 'Severe malaria', 'Malaria in pregnancy', 'Congenital malaria'],
        'Meningitis': ['Bacterial meningitis', 'Viral meningitis', 'Tuberculous meningitis', 'Cryptococcal meningitis'],
        'Sexually transmitted infections': ['Gonorrhoea', 'Syphilis', 'Chlamydia', 'Trichomoniasis', 'Genital herpes', 'Genital warts', 'Chancroid'],
        'The plague': ['Bubonic plague', 'Pneumonic plague', 'Septicaemic plague'],
        'Tuberculosis': ['Pulmonary tuberculosis', 'Extrapulmonary tuberculosis', 'TB/HIV co-infection', 'Drug-resistant TB (MDR-TB)'],
        // Malignancies
        'Anal cancer': ['Squamous cell carcinoma of the anus'],
        'Astrocytomas': ['Low-grade astrocytoma', 'High-grade astrocytoma (glioblastoma)'],
        'Carcinoma of the Breast': ['Early breast cancer', 'Locally advanced breast cancer', 'Metastatic breast cancer'],
        'Cervical cancer': ['Cervical intraepithelial neoplasia (CIN)', 'Stage I cervical cancer', 'Stage II cervical cancer', 'Stage III–IV cervical cancer'],
        'Colorectal carcinoma': ['Stage I colorectal cancer', 'Stage II colorectal cancer', 'Stage III colorectal cancer', 'Stage IV colorectal cancer'],
        'endometrial cancer': ['Endometrial adenocarcinoma'],
        'Gastric cancer': ['Early gastric cancer', 'Advanced gastric cancer'],
        'leukaemias': ['Acute lymphoblastic leukaemia (ALL)', 'Acute myeloid leukaemia (AML)', 'Chronic lymphocytic leukaemia (CLL)', 'Chronic myeloid leukaemia (CML)'],
        'Lung cancer': ['Small cell lung cancer', 'Non-small cell lung cancer'],
        'lymphomas': ['Hodgkin lymphoma', 'Non-Hodgkin lymphoma'],
        'Nasopharyngeal carcinoma': ['Nasopharyngeal carcinoma'],
        'non-melanoma skin cancer': ['Basal cell carcinoma', 'Squamous cell carcinoma of the skin'],
        'Oesophageal Cacinoma': ['Squamous cell carcinoma of the oesophagus', 'Adenocarcinoma of the oesophagus'],
        'Other head and neck cancer': ['Laryngeal cancer', 'Oral cavity cancer', 'Salivary gland cancer'],
        'Ovarian cancer': ['Epithelial ovarian cancer'],
        'Paediatric cancer': ['Wilms\' tumour (nephroblastoma)', 'Retinoblastoma', 'Neuroblastoma', 'Medulloblastoma'],
        'pancreatic cancer': ['Adenocarcinoma of the pancreas'],
        'penile cancer': ['Squamous cell carcinoma of the penis'],
        'prostate cancer': ['Localised prostate cancer', 'Locally advanced prostate cancer', 'Metastatic prostate cancer'],
        'testicular cancer': ['Seminoma', 'Non-seminomatous germ cell tumour'],
        'thyroid cancer': ['Papillary thyroid carcinoma', 'Follicular thyroid carcinoma', 'Medullary thyroid carcinoma'],
        'vulval cancer': ['Squamous cell carcinoma of the vulva'],
        // Obstetric & Gynaecological conditions
        'Abortion': ['Threatened abortion', 'Inevitable abortion', 'Incomplete abortion', 'Septic abortion', 'Missed abortion'],
        'Antenatal care': ['Routine antenatal care', 'High-risk pregnancy monitoring'],
        'Antepartum haemorrhage (APH)': ['Placenta praevia', 'Placental abruption'],
        'Medical disease in pregnancy': ['Hypertension in pregnancy', 'Diabetes in pregnancy', 'Anaemia in pregnancy', 'Malaria in pregnancy', 'HIV in pregnancy'],
        'Menstrual disorders': ['Dysmenorrhoea', 'Menorrhagia', 'Amenorrhoea', 'Polycystic ovary syndrome (PCOS)'],
        'Normal labour': ['First stage of labour', 'Second stage of labour', 'Third stage of labour'],
        'Postpartum haemorrhage (PPH)': ['Primary PPH', 'Secondary PPH'],
        'Pre-eclapsia and eclampsia': ['Pre-eclampsia', 'Severe pre-eclampsia', 'Eclampsia', 'HELLP syndrome'],
        // Poisoning
        'Management of a poisned patient': ['General approach to poisoning', 'Gastric decontamination', 'Antidote therapy'],
        'treatment of specific common poisoning': ['Organophosphate poisoning', 'Paracetamol overdose', 'Carbon monoxide poisoning', 'Snake bite', 'Alcohol intoxication', 'Rodenticide poisoning'],
        // Surgical conditions
        'Acute mumps orchitis': ['Orchitis management'],
        'Bites': ['Dog bite', 'Snake bite', 'Insect bite', 'Human bite'],
        'Hydrocele': ['Congenital hydrocele', 'Secondary hydrocele'],
        'injuries': ['Head injury', 'Chest injury', 'Abdominal injury', 'Fractures', 'Burns', 'Soft tissue injuries'],
        'Strangulated hernia': ['Inguinal hernia', 'Femoral hernia', 'Umbilical hernia'],
        'Testicular torsion': ['Testicular torsion'],
        'testicular tumours': ['Seminoma', 'Teratoma'],
        'varicocele': ['Varicocele'],
        // Dental conditions
        'Facial fractures': ['Mandibular fracture', 'Maxillary fracture', 'Zygomatic fracture'],
        'Hard tissue conditions': ['Dental caries', 'Dental abscess', 'Periodontitis', 'Tooth erosion'],
        'Soft tissue conditions': ['Aphthous ulcers', 'Ranula', 'Epulis', 'Sialadenitis', "Ludwig's angina"],
        'Tumors-benign': ['Ameloblastoma', 'Fibroma', 'Papilloma', 'Dentigerous cyst'],
        'Tumors-malignant': ['Oral squamous cell carcinoma', 'Mucoepidermoid carcinoma'],
    };

export const DIAGNOSIS_LEVEL2_BY_LEVEL1: Record<string, string[]> = {
            'Anaemia And Nutritional Conditions': [
                'Anaemia',
                'Malnutrition',
                'Vitamin deficiencies',
            ],
            'Cardiovascular Disorders': [
                'Angina pectoris',
                'Cardiac arrhythmias',
                'Cardiopulmonary resuscitation and advanced cardiac life support',
                'Congestive heart failure',
                'Hypertension',
                'Infective endocarditis',
                'Myocardial infarction',
                'Pulmonery oedema',
                'Rheumatic fever',
            ],
            'Conditions Of The Ear, Nose And Oropharynx': [
                'Ear conditions',
                'Nasal diseases',
                'oral disease',
                'Pharyngeal diseases',
            ],
            'Dermatological Conditions': [
                'bacterial infections',
                'Fungal Infection',
                'Parasitic infections',
                'viral skin infections',
            ],
            'Disorders Of The Renal System': [
                'GLOMERULAR DISORDERS',
                'Catheter-related bloodstream infections (CRBSI)',
                'hypertension',
                'Metabolic disorders',
                'Renal and pancreatic transplant',
            ],
            'Urology disorders': [
                'Renal and pancreatic transplant',
            ],
            'Eye Disease': [
                'Glaucoma',
                'ocular emergencies',
                'Optics & refraction (Refractive errors and low vision)',
                'strabismus (squint)',
                'systemic eye disease and the eye',
                'the red eye',
                'Trachoma',
            ],
            'Gastro-intestinal conditions': [
                'Abdominal Pain',
                'Cholera',
                'Diarrhoea',
                'Dysentery',
                'Epilepsy',
                'Febrile Convulsions',
                'Giardiasis',
                'Helminth Infestation',
                'Mental health and psychiatric illnesses',
                'Mood disorders',
                'Pyschotic Disorder',
                'Rabies',
            ],
            'Infections': [
                'Anthrax',
                'Malaria',
                'Meningitis',
                'Sexually transmitted infections',
                'The plague',
                'Tuberculosis',
                'Cholera',
            ],
            'Malignancies': [
                'Anal cancer',
                'Astrocytomas',
                'Carcinoma of the Breast',
                'Cervical cancer',
                'Colorectal carcinoma',
                'endometrial cancer',
                'Gastric cancer',
                'leukaemias',
                'Lung cancer',
                'lymphomas',
                'Nasopharyngeal carcinoma',
                'non-melanoma skin cancer',
                'Oesophageal Cacinoma',
                'Other head and neck cancer',
                'Ovarian cancer',
                'Paediatric cancer',
                'pancreatic cancer',
                'penile cancer',
                'prostate cancer',
                'testicular cancer',
                'thyroid cancer',
                'vulval cancer',
            ],
            'Orthopedic conditions': [
                'Renal and pancreatic transplant',
            ],
            'Obstetric & Gynaecological conditions': [
                'Abortion',
                'Antenatal care',
                'Antepartum haemorrhage (APH)',
                'Lower obstructive airway diseases',
                'medical abortion (termination of pregnancy)',
                'Medical disease in pregnancy',
                'Menstrual disorders',
                'Normal labour',
                'Postpartum haemorrhage (PPH)',
                'Pre-eclapsia and eclampsia',
                'respiratory tract infections',
                'The plague',
                'Unconscious obstetric patient',
            ],
            'Poisoning': [
                'Management of a poisned patient',
                'treatment of specific common poisoning',
            ],
            'Surgical conditions': [
                'Acute mumps orchitis',
                'Bites',
                'Hydrocele',
                'injuries',
                'Strangulated hernia',
                'Testicular torsion',
                'testicular tumours',
                'varicocele',
            ],
            'Haematological conditions': [
                'Renal and pancreatic transplant',
            ],
            'Dental conditions': [
                'Facial fractures',
                'Hard tissue conditions',
                'Soft tissue conditions',
                'Tumors-benign',
                'Tumors-malignant',
            ],
            'Mental health and psychiatric disorders': [],
            'Endocrine disorders': [],
        }

export const DIAGNOSIS_LEVEL3_BY_LEVEL2: Record<string, string[]> = {
            // Anaemia And Nutritional Conditions
            'Anaemia': ['Iron deficiency anaemia', 'Megaloblastic anaemia', 'Normocytic anaemia', 'Aplastic anaemia', 'Haemolytic anaemia', 'Sickle cell anaemia'],
            'Malnutrition': ['Kwashiorkor', 'Marasmus', 'Marasmic kwashiorkor', 'Wasting', 'Stunting', 'Obesity'],
            'Vitamin deficiencies': ['Vitamin A deficiency', 'Vitamin B1 (Thiamine) deficiency', 'Vitamin B12 deficiency', 'Vitamin C deficiency (Scurvy)', 'Vitamin D deficiency (Rickets)'],
            // Cardiovascular Disorders
            'Angina pectoris': ['Stable angina', 'Unstable angina'],
            'Cardiac arrhythmias': ['Atrial fibrillation', 'Atrial flutter', 'Supraventricular tachycardia', 'Ventricular tachycardia', 'Ventricular fibrillation', 'Heart block', 'Sinus bradycardia'],
            'Cardiopulmonary resuscitation and advanced cardiac life support': ['Basic life support', 'Advanced cardiac life support', 'Post-resuscitation care'],
            'Congestive heart failure': ['Left ventricular failure', 'Right ventricular failure', 'Biventricular failure'],
            'Hypertension': ['Mild hypertension', 'Moderate hypertension', 'Severe hypertension', 'Hypertensive emergency', 'Hypertensive urgency'],
            'Infective endocarditis': ['Native valve endocarditis', 'Prosthetic valve endocarditis'],
            'Myocardial infarction': ['ST-elevation myocardial infarction (STEMI)', 'Non-ST-elevation myocardial infarction (NSTEMI)'],
            'Pulmonery oedema': ['Acute pulmonary oedema'],
            'Rheumatic fever': ['Acute rheumatic fever', 'Rheumatic heart disease'],
            // Conditions Of The Ear, Nose And Oropharynx
            'Ear conditions': ['Acute otitis media', 'Chronic suppurative otitis media', 'Otitis externa', 'Serous otitis media', 'Hearing loss'],
            'Nasal diseases': ['Allergic rhinitis', 'Epistaxis', 'Acute sinusitis', 'Chronic sinusitis', 'Nasal polyps'],
            'oral disease': ['Gingivitis', 'Periodontitis', 'Oral candidiasis', 'Aphthous ulcers', 'Dental abscess'],
            'Pharyngeal diseases': ['Acute pharyngitis', 'Tonsillitis', 'Peritonsillar abscess', 'Epiglottitis'],
            // Dermatological Conditions
            'bacterial infections': ['Impetigo', 'Cellulitis', 'Erysipelas', 'Folliculitis', 'Boil (furuncle)', 'Carbuncle', 'Leprosy'],
            'Fungal Infection': ['Tinea capitis', 'Tinea corporis (ringworm)', 'Tinea pedis (athlete\'s foot)', 'Pityriasis versicolor', 'Candidiasis'],
            'Parasitic infections': ['Scabies', 'Pediculosis (lice)', 'Cutaneous larva migrans'],
            'viral skin infections': ['Herpes zoster (shingles)', 'Herpes simplex', 'Chickenpox', 'Warts', 'Molluscum contagiosum'],
            // Disorders Of The Renal System
            'GLOMERULAR DISORDERS': ['Acute glomerulonephritis', 'Nephrotic syndrome', 'Chronic kidney disease'],
            'Catheter-related bloodstream infections (CRBSI)': ['Prevention of CRBSI', 'Treatment of CRBSI'],
            'hypertension': ['Renovascular hypertension', 'Renal hypertension'],
            'Metabolic disorders': ['Renal calculi (kidney stones)', 'Gout', 'Hyperuricaemia'],
            'Renal and pancreatic transplant': ['Pre-transplant management', 'Post-transplant care', 'Rejection management'],
            // Eye Disease
            'Glaucoma': ['Primary open-angle glaucoma', 'Acute angle-closure glaucoma', 'Secondary glaucoma', 'Congenital glaucoma'],
            'ocular emergencies': ['Chemical eye injury', 'Penetrating eye injury', 'Retinal detachment', 'Central retinal artery occlusion'],
            'Optics & refraction (Refractive errors and low vision)': ['Myopia', 'Hyperopia', 'Astigmatism', 'Presbyopia', 'Low vision'],
            'strabismus (squint)': ['Esotropia', 'Exotropia', 'Mixed strabismus'],
            'systemic eye disease and the eye': ['Diabetic retinopathy', 'Hypertensive retinopathy', 'HIV-related eye disease', 'Thyroid eye disease'],
            'the red eye': ['Conjunctivitis', 'Keratitis', 'Anterior uveitis', 'Episcleritis'],
            'Trachoma': ['Active trachoma', 'Cicatricial trachoma', 'Trachomatous trichiasis'],
            // Gastro-intestinal conditions
            'Abdominal Pain': ['Acute appendicitis', 'Peptic ulcer disease', 'Irritable bowel syndrome', 'Intestinal obstruction', 'Cholecystitis', 'Pancreatitis'],
            'Cholera': ['Cholera (severe dehydration)', 'Cholera (some dehydration)', 'Cholera (no dehydration)'],
            'Diarrhoea': ['Acute watery diarrhoea', 'Persistent diarrhoea', 'Chronic diarrhoea'],
            'Dysentery': ['Amoebic dysentery', 'Bacillary dysentery (Shigellosis)'],
            'Epilepsy': ['Generalised tonic-clonic seizures', 'Absence seizures', 'Partial seizures', 'Status epilepticus'],
            'Febrile Convulsions': ['Simple febrile convulsions', 'Complex febrile convulsions'],
            'Giardiasis': ['Giardia intestinalis infection'],
            'Helminth Infestation': ['Ascariasis', 'Hookworm infection', 'Tapeworm (Taeniasis)', 'Trichuriasis', 'Strongyloides'],
            'Mental health and psychiatric illnesses': ['Major depressive disorder', 'Anxiety disorder', 'Schizophrenia', 'Bipolar disorder'],
            'Mood disorders': ['Major depressive disorder', 'Persistent depressive disorder (dysthymia)', 'Bipolar I disorder', 'Bipolar II disorder'],
            'Pyschotic Disorder': ['Schizophrenia', 'Schizophreniform disorder', 'Brief psychotic disorder', 'Schizoaffective disorder'],
            'Rabies': ['Post-exposure prophylaxis', 'Established rabies'],
            // Infections
            'Anthrax': ['Cutaneous anthrax', 'Inhalation anthrax', 'Gastrointestinal anthrax'],
            'Malaria': ['Uncomplicated malaria', 'Severe malaria', 'Malaria in pregnancy', 'Congenital malaria'],
            'Meningitis': ['Bacterial meningitis', 'Viral meningitis', 'Tuberculous meningitis', 'Cryptococcal meningitis'],
            'Sexually transmitted infections': ['Gonorrhoea', 'Syphilis', 'Chlamydia', 'Trichomoniasis', 'Genital herpes', 'Genital warts', 'Chancroid'],
            'The plague': ['Bubonic plague', 'Pneumonic plague', 'Septicaemic plague'],
            'Tuberculosis': ['Pulmonary tuberculosis', 'Extrapulmonary tuberculosis', 'TB/HIV co-infection', 'Drug-resistant TB (MDR-TB)'],
            // Malignancies
            'Anal cancer': ['Squamous cell carcinoma of the anus'],
            'Astrocytomas': ['Low-grade astrocytoma', 'High-grade astrocytoma (glioblastoma)'],
            'Carcinoma of the Breast': ['Early breast cancer', 'Locally advanced breast cancer', 'Metastatic breast cancer'],
            'Cervical cancer': ['Cervical intraepithelial neoplasia (CIN)', 'Stage I cervical cancer', 'Stage II cervical cancer', 'Stage III–IV cervical cancer'],
            'Colorectal carcinoma': ['Stage I colorectal cancer', 'Stage II colorectal cancer', 'Stage III colorectal cancer', 'Stage IV colorectal cancer'],
            'endometrial cancer': ['Endometrial adenocarcinoma'],
            'Gastric cancer': ['Early gastric cancer', 'Advanced gastric cancer'],
            'leukaemias': ['Acute lymphoblastic leukaemia (ALL)', 'Acute myeloid leukaemia (AML)', 'Chronic lymphocytic leukaemia (CLL)', 'Chronic myeloid leukaemia (CML)'],
            'Lung cancer': ['Small cell lung cancer', 'Non-small cell lung cancer'],
            'lymphomas': ['Hodgkin lymphoma', 'Non-Hodgkin lymphoma'],
            'Nasopharyngeal carcinoma': ['Nasopharyngeal carcinoma'],
            'non-melanoma skin cancer': ['Basal cell carcinoma', 'Squamous cell carcinoma of the skin'],
            'Oesophageal Cacinoma': ['Squamous cell carcinoma of the oesophagus', 'Adenocarcinoma of the oesophagus'],
            'Other head and neck cancer': ['Laryngeal cancer', 'Oral cavity cancer', 'Salivary gland cancer'],
            'Ovarian cancer': ['Epithelial ovarian cancer'],
            'Paediatric cancer': ['Wilms\' tumour (nephroblastoma)', 'Retinoblastoma', 'Neuroblastoma', 'Medulloblastoma'],
            'pancreatic cancer': ['Adenocarcinoma of the pancreas'],
            'penile cancer': ['Squamous cell carcinoma of the penis'],
            'prostate cancer': ['Localised prostate cancer', 'Locally advanced prostate cancer', 'Metastatic prostate cancer'],
            'testicular cancer': ['Seminoma', 'Non-seminomatous germ cell tumour'],
            'thyroid cancer': ['Papillary thyroid carcinoma', 'Follicular thyroid carcinoma', 'Medullary thyroid carcinoma'],
            'vulval cancer': ['Squamous cell carcinoma of the vulva'],
            // Obstetric & Gynaecological conditions
            'Abortion': ['Threatened abortion', 'Inevitable abortion', 'Incomplete abortion', 'Septic abortion', 'Missed abortion'],
            'Antenatal care': ['Routine antenatal care', 'High-risk pregnancy monitoring'],
            'Antepartum haemorrhage (APH)': ['Placenta praevia', 'Placental abruption'],
            'Lower obstructive airway diseases': ['Asthma in pregnancy', 'Chronic obstructive pulmonary disease'],
            'medical abortion (termination of pregnancy)': ['First trimester medical abortion', 'Second trimester medical abortion'],
            'Medical disease in pregnancy': ['Hypertension in pregnancy', 'Diabetes in pregnancy', 'Anaemia in pregnancy', 'Malaria in pregnancy', 'HIV in pregnancy'],
            'Menstrual disorders': ['Dysmenorrhoea', 'Menorrhagia', 'Amenorrhoea', 'Polycystic ovary syndrome (PCOS)'],
            'Normal labour': ['First stage of labour', 'Second stage of labour', 'Third stage of labour'],
            'Postpartum haemorrhage (PPH)': ['Primary PPH', 'Secondary PPH'],
            'Pre-eclapsia and eclampsia': ['Pre-eclampsia', 'Severe pre-eclampsia', 'Eclampsia', 'HELLP syndrome'],
            'respiratory tract infections': ['Upper respiratory tract infection', 'Lower respiratory tract infection', 'Pneumonia'],
            'Unconscious obstetric patient': ['Eclampsia', 'Severe sepsis in pregnancy', 'Other obstetric emergency'],
            // Poisoning
            'Management of a poisned patient': ['General approach to poisoning', 'Gastric decontamination', 'Antidote therapy'],
            'treatment of specific common poisoning': ['Organophosphate poisoning', 'Paracetamol overdose', 'Carbon monoxide poisoning', 'Snake bite', 'Alcohol intoxication', 'Rodenticide poisoning'],
            // Surgical conditions
            'Acute mumps orchitis': ['Orchitis management'],
            'Bites': ['Dog bite', 'Snake bite', 'Insect bite', 'Human bite'],
            'Hydrocele': ['Congenital hydrocele', 'Secondary hydrocele'],
            'injuries': ['Head injury', 'Chest injury', 'Abdominal injury', 'Fractures', 'Burns', 'Soft tissue injuries'],
            'Strangulated hernia': ['Inguinal hernia', 'Femoral hernia', 'Umbilical hernia'],
            'Testicular torsion': ['Testicular torsion'],
            'testicular tumours': ['Seminoma', 'Teratoma'],
            'varicocele': ['Varicocele'],
            // Dental conditions
            'Facial fractures': ['Mandibular fracture', 'Maxillary fracture', 'Zygomatic fracture'],
            'Hard tissue conditions': ['Dental caries', 'Dental abscess', 'Periodontitis', 'Tooth erosion'],
            'Soft tissue conditions': ['Aphthous ulcers', 'Ranula', 'Epulis', 'Sialadenitis', "Ludwig's angina"],
            'Tumors-benign': ['Ameloblastoma', 'Fibroma', 'Papilloma', 'Dentigerous cyst'],
            'Tumors-malignant': ['Oral squamous cell carcinoma', 'Mucoepidermoid carcinoma'],
        }
